
// Generated sitemap routes - do not edit manually
export const routes = [
  "/",
  "/fonts",
  "/pairs",
  "/licenses",
  "/about",
  "/contact",
  "/terms",
  "/font-example",
  "/dynamic-fonts",
  "/honk-font",
  "/fonts/0",
  "/fonts/1",
  "/fonts/2",
  "/fonts/3",
  "/fonts/4",
  "/fonts/5",
  "/fonts/6",
  "/fonts/7",
  "/fonts/8",
  "/fonts/9",
  "/fonts/0/family",
  "/fonts/1/family",
  "/fonts/2/family",
  "/fonts/3/family",
  "/fonts/4/family",
  "/fonts/5/family",
  "/fonts/6/family",
  "/fonts/7/family",
  "/fonts/8/family",
  "/fonts/9/family"
];
